apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-registration-bot
  labels:
    app: event-registration-bot
  namespace: discord-bot
spec:
  selector:
    matchLabels:
      app: event-registration-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: event-registration-bot
    spec:
      containers:
        - name: event-registration-bot
          image: ghcr.io/technotut/discord-event-registrator-forgc:master
          imagePullPolicy: Always
      restartPolicy: Always
