apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-registration-bot
  labels:
    app: event-registration-bot
  namespace: discord-bot
spec:
  selector:
    matchLabels:
      app: event-registration-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: event-registration-bot
    spec:
      containers:
        - name: event-registration-bot
          image: ghcr.io/technotut/discord-event-registrator-forgc:master
          imagePullPolicy: Always
          env:
            - name: CALENDAR_ID
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: CALENDAR_ID
            - name: LOG_CH_ID
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: LOG_CH_ID
            - name: OBSERVE_CH_ID
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: OBSERVE_CH_ID
            - name: GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: GUILD_ID
            - name: EVENT_DB_PATH
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: EVENT_DB_PATH
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: der-env-split
                  key: DISCORD_TOKEN
          volumeMounts:
            - name: credentials
              mountPath: "/usr/src/.local"
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: der-credentials
            items:
              - key: credentials.json
                path: credentials.json
      restartPolicy: Always
