apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-registrator-bot
  labels:
    app: event-registrator-bot
  namespace: event-registrator-bot
spec:
  selector:
    matchLabels:
      app: event-registrator-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: event-registrator-bot
    spec:
      containers:
        - name: event-registrator-bot
          image: ghcr.io/technotut/Discord-Event-Registrator-forGC:main
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 256Mi
      restartPolicy: Always
